// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace monokaiTheme
{
    internal sealed partial class Vsix
    {
        public const string Id = "monokaiTheme.d27bb130-a3b9-41b3-9671-033e9061155d";
        public const string Name = "monokai Theme";
        public const string Description = @"monokai theme for VS 2022";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Kristoffer Hopland";
        public const string Tags = "";
    }
}
